### PR TITLE
[WIP] Update to MySQLI and Code Optimizations

### PR DESCRIPTION
**Pull request by TekkitCommando**
This is the PR that updates from the old MySQL functions in PHP to the new MySQLI API. I checked the WHOLE codebase TWICE so I should have updated all MySQL functions but please let me know if you spot some that I didn't update.

This PR will also have some code improvements such as custom functions for the mysqli logic for neater code and to prevent repeated code as well as general code improvements.

If there is any bugs with this PR (although there shouldn't be because they are just updates and code improvements) please comment below or send an issue to my repo for GPX instead of main until this PR is pulled.

Track progress for this PR with this checklist (plus I will comment @devryan when it is finished.) 
- [ ] Finish MySQLi support
- [ ] Code optimizations

### CODE REVIEW

**Comment by xognovalis** [comment]
https://github.com/bytepowered/GamePanelX-V3/blob/master/install/install_actions.php#L20

Forgot to update the `function_exists`.

**Comment by xognovalis** [comment]
Do **not** accept pull request.

MySQLI not implemented correctly.

For the procedural style, the queries are missing the $link parameter.

**Comment by TekkitCommando** [comment]
@xognovalis I noticed that as well but it was already late at night. I will have the fix made later today. Sorry.

**Comment by devryan** [comment]
No need for apologies!  Let me know when it's all solid :+1:

**Comment by TekkitCommando** [comment]
@devryan @xognovalis Just to let you know and not leave you in the dark, I am working on a course project rn and that is why I haven't committed anything so far. I will be committing some code optimizations today but it will be after I finish my PHP course project that I will finish the MySQLI update (which won't take to long.)

**Comment by TekkitCommando** [comment]
@devryan Just to let you know so that after we merge this pull request and you want to update, I am going to setup a db connection file in the includes folder and have the files require it for running. This will prevent us from having to create a new connection multiple times.

**Comment by TekkitCommando** [comment]
Alright did a lot of updating to the mysqli functions, will be finishing it tonight or after class tomorrow.

**Comment by xognovalis** [comment]
ayyyy :+1:

**Comment by devryan** [comment]
What's the status on this one?

**Comment by TekkitCommando** [comment]
@devryan got it pretty updated but I am really busy with work rn so I will just close this for now and resend the PR when I finish it.

**Comment by TheDiamondYT1** [comment]
Or just leave it open...

**Pull request closed without merging**
